### ISSUE TITLE
getCases: TypeError after upgrading adaptor version 

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/unicef-cambodia#78]
## Describe the bug
We upgraded the adaptor version for this old [job](https://www.openfn.org/projects/p56pbe/jobs/jywaga). We are running into [this](https://www.openfn.org/projects/p56pbe/runs/0618a529-b7f4-7282-87b2-9fff4d22df28) error, can you help us clean up the job?

## state 
NA
See LP `Primero V2 Cambodia Demo API user`

## To Reproduce
1. Here is a link to a failed run on OpenFn.org which is indicative of the bug: https://www.openfn.org/projects/p56pbe/runs/0618a529-b7f4-7282-87b2-9fff4d22df28

### expression.js
**PLEASE MAKE SURE TO ONLY EDIT THE JOBS IN THE `V2` DIRECTORY... the others in the main directory are live on prod.**
https://www.openfn.org/projects/p56pbe/jobs/jywaga
https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f1-j1-getPrimeroCases.js

## To test/resolve
Feel free to re-run this run on prod to retrigger the flow: https://www.openfn.org/projects/p56pbe/runs/0618a529-b7f4-7282-87b2-9fff4d22df28

**Comment by aleksa-krolls** [comment]
@lakhassane pls prioritize this morning and let @daissatou2 know when finished. 

fyi, issue looks related to date parsing and the cursor we set for the time time the get job runs.... wondering if we should change the cursor date time to the case `last_updated` if the current cursor date is not available.

**Comment by lakhassane** [comment]
@aleksa-krolls I have questions in here. Do you know what was the reason for doing this: https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f1-j1-getPrimeroCases.js#L3-L21

Because without a state this job cannot work (because state.data does not exist). Could you clarify what was the intention so I can know how to clean?

**Comment by lakhassane** [comment]
@daissatou2 here is the last run: https://www.openfn.org/projects/p56pbe/runs/0618ba8a-8315-7c4e-8a25-612e054743f8. Corrected how we handle the different cursor and the date parsing.  

As discussed with Aïcha, we might not need to keep a manualCursor since they are directly specified in the filtering option for the `getCase()`
