### ISSUE TITLE
Add mappings to logs for upsert jobs

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/unicef-cambodia#82]
# Feature Request

## Background, context, and business value

Please update the logs for the jobs below to show all the field mappings. This will make it easier for us to verify the mappings. 

**DO NOT DELETE OLD LOGS. Please comment out the old logging in case the client wants us to change this back (they wanted very specific logging in the past).** 

Jobs to update: 
https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f1-j2-casesToOscar.js
https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f2-j2-upsertCasesToPrimero.js

The Primero-Progres job logging is a great example: 
https://www.openfn.org/projects/primero-progres-v4-staging/runs/06193d4c-d328-7fb4-9422-1dc153692154

**Comment by lakhassane** [comment]
@daissatou2 logs are added

**Comment by daissatou2** [comment]
Hi @lakhassane can you please double check that this is implemented? Some fields are still missing..
For example, in [this](https://www.openfn.org/projects/primero-oscar-cambodia-io-staging/runs/061a8979-8263-7537-bc54-f37797c126ec) run `service_type` is missing.

**Comment by lakhassane** [comment]
@daissatou2 please could you tell where in the logs we shouild have `service_type`? There are many different logs in the run :confused:

Also there is no service_type in the data we send to primero https://github.com/OpenFn/unicef-cambodia/blob/master/jobs/V2/f2-j2-upsertCasesToPrimero.js#L507-L560

**Comment by aleksa-krolls** [comment]
@lakhassane The issue is right now the logs are all hardcoded... this custom logging was originally for security reasons, but it makes testing difficult because we can't see ALL the data points being exchanged. Please comment these logs out (for now... we will add them back later before go-live). 

Then, add new logs so that we see the raw payload of ALL fields that are being passed between systems. 
Show all `state.data` for
(1) `Data provided by Oscar` and... 
(2)`Data provided to Primero for upload `upsertCase`

This will enable @daissatou2 to critique the mappings more easily and ensure all necessary data points are being exchange. Ping me on Slack if you want to talk this through.

**Comment by lakhassane** [comment]
@daissatou2 I updated logs to show all the content of `state.data` instead of hardcoding. You should be good to go.
